import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:get/get.dart';
import 'package:image_picker/image_picker.dart';
import 'package:sarvam/controller/client_enrollment/enrollment_options.dart';
import 'package:sarvam/controller/client_enrollment/enrollment_uploads.dart';
import 'package:sarvam/controller/client_enrollment_controller.dart';
import 'package:sarvam/view/FDO/new_member_create/widgets/enrollment_field_widgets.dart';
import 'package:sarvam/services/enrollment_api_service.dart';

/// Resolves a stored `fileUrl` (a bare, private-bucket object key for any
/// document uploaded through this app) to a signed, viewable URL before
/// rendering it — a raw `Image.network(key)` always fails ("Could not load
/// this document") since the bucket isn't public. Cached process-wide by
/// key so re-opening the same document, or the same [Obx] rebuilding, don't
/// re-request a fresh signed URL every time.
class _SignedImage extends StatefulWidget {
  const _SignedImage({
    required this.api,
    required this.rawUrlOrKey,
    this.errorWidget,
  });

  final EnrollmentApiService api;
  final String rawUrlOrKey;
  final Widget? errorWidget;

  static final Map<String, Future<String?>> _cache = {};

  @override
  State<_SignedImage> createState() => _SignedImageState();
}

class _SignedImageState extends State<_SignedImage> {
  late Future<String?> _future;

  @override
  void initState() {
    super.initState();
    _future = _SignedImage._cache.putIfAbsent(
      widget.rawUrlOrKey,
      () => widget.api.resolveFileUrl(widget.rawUrlOrKey),
    );
  }

  @override
  Widget build(BuildContext context) => FutureBuilder<String?>(
    future: _future,
    builder: (context, snapshot) {
      if (snapshot.connectionState != ConnectionState.done) {
        return const Center(child: CircularProgressIndicator(strokeWidth: 2));
      }
      final url = snapshot.data;
      if (url == null || url.isEmpty) {
        return widget.errorWidget ??
            const Icon(Icons.broken_image_outlined, color: Color(0xFFA9C9B7));
      }
      return Image.network(
        url,
        fit: BoxFit.cover,
        errorBuilder: (_, __, ___) =>
            widget.errorWidget ??
            const Icon(Icons.broken_image_outlined, color: Color(0xFFA9C9B7)),
        loadingBuilder: (context, child, progress) =>
            progress == null ? child : const Center(child: CircularProgressIndicator(strokeWidth: 2)),
      );
    },
  );
}

const _clientDocLabels = {
  EnrollmentOptions.docClientPhoto: 'Member / Client Photo',
  EnrollmentOptions.docAadhaarFront: 'Aadhaar Front',
  EnrollmentOptions.docAadhaarBack: 'Aadhaar Back',
  EnrollmentOptions.docPanCard: 'PAN Card',
  EnrollmentOptions.docVoterId: 'Voter ID Front',
  EnrollmentOptions.docVoterIdBack: 'Voter ID Back',
  EnrollmentOptions.docBankPassbook: 'Bank Passbook',
  EnrollmentOptions.docSmartCardFront: 'Smart Card Front',
  EnrollmentOptions.docSmartCardBack: 'Smart Card Back',
};

const _coApplicantDocLabels = {
  EnrollmentOptions.docCoApplicantPhoto: 'Co-Applicant Photo',
  EnrollmentOptions.docCoApplicantAadhaarFront: 'Co-Applicant Aadhaar Front',
  EnrollmentOptions.docCoApplicantAadhaarBack: 'Co-Applicant Aadhaar Back',
  EnrollmentOptions.docCoApplicantPanCard: 'Co-Applicant PAN Card',
  EnrollmentOptions.docCoApplicantVoterId: 'Co-Applicant Voter ID Front',
  EnrollmentOptions.docCoApplicantVoterIdBack: 'Co-Applicant Voter ID Back',
  EnrollmentOptions.docCoApplicantOtherIdFront: 'Co-Applicant Other ID Front',
  EnrollmentOptions.docCoApplicantOtherIdBack: 'Co-Applicant Other ID Back',
};

const _residenceDocLabels = {
  EnrollmentOptions.docHouseImage1: 'House Image 1',
  EnrollmentOptions.docHouseImage2: 'House Image 2',
  EnrollmentOptions.docHouseImage3: 'House Image 3',
  EnrollmentOptions.docGasBill: 'NOC (Gas Bill)',
  EnrollmentOptions.docNocImage1: 'NOC Image 1',
  EnrollmentOptions.docNocImage2: 'NOC Image 2',
  EnrollmentOptions.docNocImage3: 'NOC Image 3',
  // Auto-generated by fetchLocation()/generateAndUploadLocationQr() once
  // lat/long settle — included here (not just the status line below) so the
  // FDO can actually see/re-view the QR image, matching the web app's
  // residence-verification card grid instead of a bare "uploaded" caption.
  EnrollmentOptions.docLocationQr: 'Location QR',
};

class KycDetailsTab extends StatelessWidget {
  const KycDetailsTab({super.key, required this.controller});

  final ClientEnrollmentController controller;

  @override
  Widget build(BuildContext context) => EnrollmentSectionShell(
    title: 'KYC Details',
    subtitle: 'Upload required documents for client and co-applicant verification.',
    icon: Icons.badge_outlined,
    children: [
      _uploadGroup('Client Documents', _clientDocLabels, owner: 'client'),
      SizedBox(height: 16.h),
      _uploadGroup('Co-Applicant Documents', _coApplicantDocLabels, owner: 'coApplicant'),
      SizedBox(height: 16.h),
      _uploadGroup(
        'Residence Verification',
        _residenceDocLabels,
        owner: 'client',
        subtitle: 'House Image 1, lat/long & QR required',
      ),
      SizedBox(height: 4.h),
      Obx(
        () => Column(
          children: [
            Row(
              children: [
                Expanded(
                  child: EnrollmentTextField(
                    label: 'Latitude',
                    hint: 'Auto-filled',
                    controller: TextEditingController(text: controller.latitude.value),
                    readOnly: true,
                    required: true,
                  ),
                ),
                SizedBox(width: 10.w),
                Expanded(
                  child: EnrollmentTextField(
                    label: 'Longitude',
                    hint: 'Auto-filled',
                    controller: TextEditingController(text: controller.longitude.value),
                    readOnly: true,
                    required: true,
                  ),
                ),
              ],
            ),
            SizedBox(
              width: double.infinity,
              child: FilledButton.icon(
                onPressed: controller.isLocating.value ? null : controller.fetchLocation,
                icon: controller.isLocating.value
                    ? const SizedBox(
                        width: 14,
                        height: 14,
                        child: CircularProgressIndicator(strokeWidth: 2, color: Colors.white),
                      )
                    : const Icon(Icons.my_location_outlined, size: 17),
                label: const Text('Use Current Location'),
                style: FilledButton.styleFrom(backgroundColor: enrollmentGreen),
              ),
            ),
            if (controller.mapsUrl.value.isNotEmpty) ...[
              SizedBox(height: 8.h),
              Align(
                alignment: Alignment.centerLeft,
                child: Text(
                  'Maps URL: ${controller.mapsUrl.value}',
                  style: TextStyle(fontSize: 10.5.sp, color: const Color(0xFF475569)),
                ),
              ),
            ],
            SizedBox(height: 8.h),
            if (controller.docState(EnrollmentOptions.docLocationQr)?.isUploading == true)
              Text(
                'Generating location QR…',
                style: TextStyle(fontSize: 11.sp, color: const Color(0xFF64748B)),
              )
            else if (controller.docState(EnrollmentOptions.docLocationQr)?.isUploaded == true)
              _qrPreviewPanel(),
          ],
        ),
      ),
    ],
  );

  /// Bigger, dedicated QR preview — mirrors the web app's "QR uploaded" box
  /// below the lat/long fields. The small thumbnail on the document card
  /// above is enough to confirm an upload happened, but too small to
  /// actually scan; tapping this one opens the same full-screen viewer at a
  /// size a phone camera can read, so the FDO can hand the device to someone
  /// else to scan it, or use it to double-check the pin before submitting.
  Widget _qrPreviewPanel() => Obx(() {
    final state = controller.docState(EnrollmentOptions.docLocationQr);
    final url = state?.fileUrl;
    if (url == null || url.isEmpty) return const SizedBox.shrink();
    return Builder(
      builder: (ctx) => InkWell(
        borderRadius: BorderRadius.circular(10.r),
        onTap: () => _previewDocument(ctx, state!, 'Location QR'),
        child: Container(
          width: double.infinity,
          padding: EdgeInsets.all(10.w),
          decoration: BoxDecoration(
            color: const Color(0xFFF1F8F4),
            borderRadius: BorderRadius.circular(10.r),
            border: Border.all(color: const Color(0xFFCFE9DA)),
          ),
          child: Row(
            children: [
              SizedBox(
                width: 56.w,
                height: 56.w,
                child: ClipRRect(
                  borderRadius: BorderRadius.circular(6.r),
                  child: _SignedImage(
                    api: controller.api,
                    rawUrlOrKey: url,
                    errorWidget: Icon(Icons.qr_code_2_rounded, size: 40.sp, color: enrollmentGreen),
                  ),
                ),
              ),
              SizedBox(width: 12.w),
              Expanded(
                child: Text(
                  'Tap or scan to open this location in Google Maps.',
                  style: TextStyle(fontSize: 11.sp, fontWeight: FontWeight.w600, color: const Color(0xFF164A2E)),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  });

  Widget _uploadGroup(
    String title,
    Map<String, String> docs, {
    required String owner,
    String? subtitle,
  }) => Container(
    width: double.infinity,
    decoration: BoxDecoration(
      border: Border.all(color: const Color(0xFF8ED0A6)),
      borderRadius: BorderRadius.circular(9.r),
    ),
    child: Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Container(
          width: double.infinity,
          padding: EdgeInsets.symmetric(horizontal: 12.w, vertical: 10.h),
          decoration: BoxDecoration(
            color: enrollmentGreen,
            borderRadius: BorderRadius.vertical(top: Radius.circular(8.r)),
          ),
          child: Row(
            children: [
              Expanded(
                child: Text(
                  title,
                  style: TextStyle(color: Colors.white, fontSize: 14.sp, fontWeight: FontWeight.w700),
                ),
              ),
              if (subtitle != null)
                Flexible(
                  child: Text(
                    subtitle,
                    textAlign: TextAlign.right,
                    maxLines: 2,
                    overflow: TextOverflow.ellipsis,
                    style: TextStyle(color: Colors.white70, fontSize: 9.5.sp, fontWeight: FontWeight.w600),
                  ),
                ),
            ],
          ),
        ),
        Padding(
          padding: EdgeInsets.all(10.w),
          child: Wrap(
            spacing: 10.w,
            runSpacing: 10.h,
            children: docs.entries
                .map((entry) => _docCard(entry.key, entry.value, owner: owner))
                .toList(),
          ),
        ),
      ],
    ),
  );

  void _showUploadSourceSheet(
    BuildContext context,
    String documentType,
    String label, {
    required String owner,
    required bool allowPdf,
  }) {
    showModalBottomSheet<void>(
      context: context,
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(top: Radius.circular(16)),
      ),
      builder: (bottomContext) => SafeArea(
        child: Padding(
          padding: const EdgeInsets.symmetric(vertical: 16, horizontal: 18),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                'Upload $label',
                style: const TextStyle(
                  fontSize: 16,
                  fontWeight: FontWeight.w700,
                  color: Color(0xFF063B20),
                ),
              ),
              const SizedBox(height: 14),
              ListTile(
                leading: const Icon(Icons.camera_alt_outlined, color: enrollmentGreen),
                title: const Text('Take Photo (Camera)', style: TextStyle(fontSize: 13, fontWeight: FontWeight.w600)),
                onTap: () {
                  Navigator.pop(bottomContext);
                  controller.pickAndUploadDocument(
                    documentType,
                    owner: owner,
                    source: ImageSource.camera,
                  );
                },
              ),
              const Divider(height: 1),
              ListTile(
                leading: const Icon(Icons.photo_library_outlined, color: enrollmentGreen),
                title: const Text('Choose from Photo Gallery', style: TextStyle(fontSize: 13, fontWeight: FontWeight.w600)),
                onTap: () {
                  Navigator.pop(bottomContext);
                  controller.pickAndUploadDocument(
                    documentType,
                    owner: owner,
                    source: ImageSource.gallery,
                  );
                },
              ),
              if (documentType.toLowerCase().contains('aadhaar') ||
                  documentType.toLowerCase().contains('pancard') ||
                  documentType.toLowerCase().contains('pan')) ...[
                const Divider(height: 1),
                ListTile(
                  leading: const Icon(Icons.qr_code_scanner_rounded, color: enrollmentGreen),
                  title: Text(
                    'Scan & Auto-Fill ${documentType.toLowerCase().contains('aadhaar') ? 'Aadhaar No' : 'PAN Card No'}',
                    style: const TextStyle(fontSize: 13, fontWeight: FontWeight.w700, color: enrollmentGreen),
                  ),
                  onTap: () {
                    Navigator.pop(bottomContext);
                    _showScanIdModal(context, documentType, owner: owner);
                  },
                ),
              ],
              if (allowPdf) ...[
                const Divider(height: 1),
                ListTile(
                  leading: const Icon(Icons.picture_as_pdf_outlined, color: enrollmentGreen),
                  title: const Text('Choose PDF / Document File', style: TextStyle(fontSize: 13, fontWeight: FontWeight.w600)),
                  onTap: () {
                    Navigator.pop(bottomContext);
                    controller.pickAndUploadDocument(
                      documentType,
                      owner: owner,
                      allowPdf: true,
                    );
                  },
                ),
              ],
            ],
          ),
        ),
      ),
    );
  }

  void _showScanIdModal(BuildContext context, String documentType, {required String owner}) {
    final isAadhaar = documentType.toLowerCase().contains('aadhaar');
    final title = isAadhaar ? 'Scan Aadhaar Card' : 'Scan PAN Card';
    final ctrl = TextEditingController();

    showDialog(
      context: context,
      builder: (ctx) => AlertDialog(
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(14.r)),
        title: Row(
          children: [
            const Icon(Icons.qr_code_scanner_rounded, color: enrollmentGreen),
            SizedBox(width: 8.w),
            Expanded(
              child: Text(
                title,
                style: TextStyle(fontSize: 16.sp, fontWeight: FontWeight.w800, color: const Color(0xFF063B20)),
                overflow: TextOverflow.ellipsis,
              ),
            ),
          ],
        ),
        content: SingleChildScrollView(
          child: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              isAadhaar
                  ? 'Enter or scan 12-digit Aadhaar Number:'
                  : 'Enter or scan 10-character PAN Card Number:',
              style: TextStyle(fontSize: 12.sp, color: Colors.grey[700]),
            ),
            SizedBox(height: 12.h),
            TextField(
              controller: ctrl,
              maxLength: isAadhaar ? 12 : 10,
              keyboardType: isAadhaar ? TextInputType.number : TextInputType.text,
              textCapitalization: TextCapitalization.characters,
              decoration: InputDecoration(
                hintText: isAadhaar ? '123456789012' : 'ABCDE1234F',
                border: const OutlineInputBorder(),
                prefixIcon: Icon(isAadhaar ? Icons.badge_outlined : Icons.credit_card_outlined),
              ),
            ),
          ],
        ),
      ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(ctx),
            child: const Text('Cancel'),
          ),
          ElevatedButton.icon(
            style: ElevatedButton.styleFrom(backgroundColor: enrollmentGreen, foregroundColor: Colors.white),
            icon: const Icon(Icons.check_rounded, size: 18),
            label: const Text('Auto-Fill Field'),
            onPressed: () {
              final val = ctrl.text.trim();
              if (val.isEmpty) {
                Get.snackbar('Input Required', 'Please enter a valid number.', backgroundColor: Colors.orange, colorText: Colors.white);
                return;
              }
              if (isAadhaar) {
                if (owner == 'client') {
                  controller.otherIdNoCtrl.text = val;
                } else {
                  controller.caOtherIdNoCtrl.text = val;
                }
              } else {
                if (owner == 'client') {
                  controller.pancardNoCtrl.text = val;
                } else {
                  controller.caPancardNoCtrl.text = val;
                }
              }
              Navigator.pop(ctx);
              Get.snackbar(
                'Auto-Filled',
                '${isAadhaar ? "Aadhaar Number" : "PAN Card Number"} updated successfully.',
                backgroundColor: enrollmentGreen,
                colorText: Colors.white,
              );
            },
          ),
        ],
      ),
    );
  }

  /// A single KYC document tile — image thumbnail (or a PDF/placeholder
  /// icon) with upload/view/delete actions, matching the web app's document
  /// card layout so an uploaded document can actually be seen/reviewed
  /// inline instead of only showing a checkmark.
  Widget _docCard(String documentType, String label, {required String owner}) => Obx(() {
    final state = controller.docState(documentType);
    final allowPdf = EnrollmentOptions.pdfEligibleDocumentTypes.contains(documentType);
    final isPdf = (state?.mimeType ?? '').toLowerCase().contains('pdf');
    final uploaded = state?.isUploaded == true;
    final uploading = state?.isUploading == true;

    return SizedBox(
      width: 104.w,
      child: Column(
        children: [
          Builder(
            builder: (ctx) => InkWell(
              borderRadius: BorderRadius.circular(8.r),
              onTap: uploading
                  ? null
                  : uploaded
                      ? () => _previewDocument(ctx, state!, label)
                      : () => _showUploadSourceSheet(ctx, documentType, label, owner: owner, allowPdf: allowPdf),
              child: Container(
                width: 104.w,
                height: 90.h,
                decoration: BoxDecoration(
                  color: const Color(0xFFF1F8F4),
                  borderRadius: BorderRadius.circular(8.r),
                  border: Border.all(color: const Color(0xFFCFE9DA)),
                ),
                clipBehavior: Clip.antiAlias,
                child: uploading
                    ? const Center(child: CircularProgressIndicator(strokeWidth: 2))
                    : !uploaded
                        ? Icon(Icons.image_outlined, size: 30.sp, color: const Color(0xFFA9C9B7))
                        : isPdf
                            ? Icon(Icons.picture_as_pdf_rounded, size: 30.sp, color: const Color(0xFFB91C1C))
                            : _SignedImage(
                                api: controller.api,
                                rawUrlOrKey: state!.fileUrl!,
                                errorWidget: Icon(Icons.broken_image_outlined, size: 28.sp, color: const Color(0xFFA9C9B7)),
                              ),
              ),
            ),
          ),
          SizedBox(height: 4.h),
          Text(
            label,
            textAlign: TextAlign.center,
            maxLines: 2,
            overflow: TextOverflow.ellipsis,
            style: TextStyle(fontSize: 10.sp, fontWeight: FontWeight.w600, color: const Color(0xFF164A2E)),
          ),
          SizedBox(height: 4.h),
          Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Builder(
                builder: (ctx) => _cardIconButton(
                  icon: uploaded ? Icons.refresh_rounded : Icons.upload_rounded,
                  onTap: () => _showUploadSourceSheet(ctx, documentType, label, owner: owner, allowPdf: allowPdf),
                ),
              ),
              if (uploaded) ...[
                SizedBox(width: 4.w),
                Builder(
                  builder: (ctx) => _cardIconButton(
                    icon: Icons.visibility_outlined,
                    onTap: () => _previewDocument(ctx, state!, label),
                  ),
                ),
                SizedBox(width: 4.w),
                _cardIconButton(
                  icon: Icons.delete_outline_rounded,
                  color: const Color(0xFFB91C1C),
                  onTap: () => controller.removeDocument(documentType),
                ),
              ],
            ],
          ),
        ],
      ),
    );
  });

  Widget _cardIconButton({required IconData icon, required VoidCallback onTap, Color? color}) => InkWell(
    borderRadius: BorderRadius.circular(6.r),
    onTap: onTap,
    child: Padding(
      padding: EdgeInsets.all(3.w),
      child: Icon(icon, size: 15.sp, color: color ?? enrollmentGreen),
    ),
  );

  void _previewDocument(BuildContext context, EnrollmentDocState state, String label) {
    final isPdf = (state.mimeType ?? '').toLowerCase().contains('pdf');
    final url = state.fileUrl;
    if (url == null || url.isEmpty) return;
    if (isPdf) {
      Get.snackbar(
        label,
        'This is a PDF document — use "Replace" to re-upload if needed.',
        backgroundColor: const Color(0xFF334155),
        colorText: Colors.white,
      );
      return;
    }
    showDialog<void>(
      context: context,
      builder: (ctx) => Dialog(
        insetPadding: const EdgeInsets.all(16),
        backgroundColor: Colors.transparent,
        child: Stack(
          alignment: Alignment.topRight,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.circular(12),
              child: SizedBox(
                width: 320,
                height: 320,
                child: InteractiveViewer(
                  child: _SignedImage(
                    api: controller.api,
                    rawUrlOrKey: url,
                    errorWidget: Container(
                      color: Colors.white,
                      padding: const EdgeInsets.all(24),
                      child: const Text('Could not load this document.'),
                    ),
                  ),
                ),
              ),
            ),
            IconButton(
              onPressed: () => Navigator.pop(ctx),
              icon: const CircleAvatar(
                backgroundColor: Colors.black54,
                child: Icon(Icons.close, color: Colors.white, size: 18),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
